# Generated by Django 5.2.13 on 2026-04-08 20:33

import core.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^ZU/[A-Z]{2,6}/\\d{4}/\\d{4}$', 'Must match ZU/PROG/YYYY/XXXX.')])),
                ('full_name', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('year_of_study', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.CharField(help_text='DDMMYYYY as stored for default password workflow.', max_length=20, validators=[core.validators.validate_dob_ddmmyyyy])),
                ('university', models.CharField(default='Zanzibar University', max_length=100)),
            ],
            options={
                'db_table': 'student_profiles',
                'ordering': ['registration_no'],
            },
        ),
    ]
