# Generated by Django 5.2.13 on 2026-04-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_directory', '0001_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dashboard_notes',
            field=models.TextField(blank=True, default='', help_text='Extra dashboard / admin-visible notes for this student.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hospital_department',
            field=models.ForeignKey(blank=True, help_text='Hospital department corresponding to placement / attachment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='hospital_directory.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='programme',
            field=models.CharField(help_text='Course / programme of study.', max_length=100),
        ),
    ]
