# Generated by Django 5.2.13 on 2026-04-20 05:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'university_departments',
                'ordering': ['faculty', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityFaculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'University faculties',
                'db_table': 'university_faculties',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level_of_study',
            field=models.CharField(blank=True, default='', help_text='e.g. degree, diploma, masters', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='registration_no',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^((ZU/[A-Z]{2,6}/\\d{4}/\\d{4})|(S\\d{3}))$', 'Must match ZU/PROG/YYYY/XXXX or practice student id S### (e.g. S001).')]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='students.universitydepartment'),
        ),
        migrations.AddField(
            model_name='universitydepartment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='students.universityfaculty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='students.universityfaculty'),
        ),
        migrations.AddConstraint(
            model_name='universitydepartment',
            constraint=models.UniqueConstraint(fields=('faculty', 'name'), name='uniq_university_department_per_faculty'),
        ),
    ]
