# Generated by Django 5.2.13 on 2026-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_registry_and_university_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydepartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='universityfaculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
