# Generated by Django 5.2.13 on 2026-06-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_universitydepartment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
