# Generated by Django 5.2.13 on 2026-04-20 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocumentKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'hospital_application_document_kinds',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'hospital_sponsorship_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
