# Generated by Django 5.2.13 on 2026-08-03 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('roles', models.CharField(blank=True, default='', help_text='Comma-separated roles this applies to. Blank = all roles.', max_length=300)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated keywords used for retrieval.', max_length=400)),
                ('source', models.CharField(choices=[('seed', 'Built-in'), ('learned', 'Learned from chat'), ('manual', 'Added by admin')], default='seed', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are never sent to the assistant or the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'knowledge entry',
                'verbose_name_plural': 'knowledge entries',
                'db_table': 'chatbot_knowledge_entries',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_active', 'source'], name='chatbot_kno_is_acti_9c876a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, default='', max_length=40)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('used_fallback', models.BooleanField(default=False)),
                ('matched_keys', models.CharField(blank=True, default='', help_text='Knowledge entry keys retrieved for this answer.', max_length=400)),
                ('helpful', models.BooleanField(blank=True, help_text='User rating: true = helpful, false = not helpful, null = unrated.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_interactions', to=settings.AUTH_USER_MODEL)),
                ('promoted_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_from', to='chatbot.knowledgeentry')),
            ],
            options={
                'verbose_name': 'chat interaction',
                'verbose_name_plural': 'chat interactions',
                'db_table': 'chatbot_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chatbot_int_user_id_d9b154_idx')],
            },
        ),
    ]
