# Generated by Django 5.2.13 on 2026-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('student', 'Student'), ('hod', 'Head of Department'), ('asst_director', 'Assistant Director'), ('management', 'Management'), ('hospital_admin', 'Hospital Admin'), ('univ_admin', 'University Admin'), ('employee_admin', 'Employee Admin'), ('sysadmin', 'System Admin')], default='employee', max_length=30),
        ),
    ]
