# Generated by Django 5.2.13 on 2026-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_googleidentity_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Wrong-code submissions against this grant; the code burns at the limit.'),
        ),
    ]
