# Generated by Django 5.2.13 on 2026-08-03 10:27

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresettoken_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile picture shown in the header and on the account page.', null=True, upload_to=apps.users.models.profile_photo_upload_to),
        ),
    ]
