# Generated by Django 5.2.13 on 2026-04-08 20:33

import apps.applications.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_ref', models.CharField(blank=True, help_text='Assigned on submit: APP-YYYY-XXXXX', max_length=30, null=True, unique=True)),
                ('app_type', models.CharField(choices=[('further_studies', 'Further Studies'), ('attachment', 'Field Attachment')], default='further_studies', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='draft', max_length=30)),
                ('current_stage', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('programme_applied', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sponsorship_type', models.CharField(blank=True, default='', max_length=100)),
                ('reason_for_study', models.TextField(blank=True, default='')),
                ('attachment_dept', models.CharField(blank=True, default='', max_length=100)),
                ('attachment_start', models.DateField(blank=True, null=True)),
                ('attachment_end', models.DateField(blank=True, null=True)),
                ('supervisor_requested', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=255, upload_to=apps.applications.models.document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_trail',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
