# Generated by Django 5.2.13 on 2026-04-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('hospital_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hospital_department',
            field=models.ForeignKey(blank=True, help_text='Structured hospital department (dropdown).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_requests', to='hospital_directory.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='placement_scope',
            field=models.CharField(blank=True, default='', help_text='individual | group — attachment placement mode.', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='attachment_dept',
            field=models.CharField(blank=True, default='', help_text='Legacy free-text department; prefer hospital_department when set.', max_length=100),
        ),
    ]
