# Generated by Django 5.2.13 on 2026-04-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_hospital_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-updated_at'], 'verbose_name': 'study or attachment request', 'verbose_name_plural': 'study & attachment requests'},
        ),
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'request document', 'verbose_name_plural': 'request documents'},
        ),
        migrations.AlterModelOptions(
            name='reviewtrail',
            options={'ordering': ['-reviewed_at'], 'verbose_name': 'request review entry', 'verbose_name_plural': 'request review trail'},
        ),
    ]
