# Generated by Django 5.2.13 on 2026-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='field_records_shared_at',
            field=models.DateTimeField(blank=True, help_text='When placement details were published to the university and student.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_feedback_for_university',
            field=models.TextField(blank=True, default='', help_text='HR notes forwarded to university admin with the placement record.'),
        ),
        migrations.AddField(
            model_name='application',
            name='placement_conducted_site',
            field=models.CharField(blank=True, default='', help_text='Hospital-confirmed place where field training is conducted (HR / admin).', max_length=400),
        ),
    ]
