# Generated by Django 5.2.13 on 2026-04-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_attachment_queue_use_hr_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtrail',
            name='letter_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewtrail',
            name='signature_data',
            field=models.TextField(blank=True, default='', help_text='Optional data URL or JSON from reviewer signature capture.'),
        ),
    ]
