# Generated by Django 5.2.13 on 2026-04-28 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_registry_and_university_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('staff', 'Staff member'), ('hod', 'Head of Department'), ('both', 'Staff and HOD')], default='staff', help_text='Who was notified: staff, hod, or both.', max_length=10)),
                ('message', models.TextField()),
                ('reply_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('notify_via_system', models.BooleanField(default=True)),
                ('notify_via_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='applications.application')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
