# Generated by Django — internal TM↔ADR coordination targets; widen `target` field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_add_change_request_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerequest",
            name="target",
            field=models.CharField(
                choices=[
                    ("staff", "Staff member"),
                    ("hod", "Head of Department"),
                    ("both", "Staff and HOD"),
                    ("to_adr", "Assistant Director (internal — from Top Management)"),
                    ("to_mgmt", "Top Management (internal — from Assistant Director)"),
                ],
                default="staff",
                help_text="Who was notified: staff, hod, both, or internal TM↔ADR coordination.",
                max_length=20,
            ),
        ),
    ]
