# Generated by Django 5.2.13 on 2026-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_reviewtrail_feedback_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notification_email',
            field=models.EmailField(blank=True, default='', help_text='Email address provided by the applicant on the form for receiving notifications.', max_length=254),
        ),
    ]
