# Generated by Django 5.2.13 on 2026-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_add_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hod_forwarded_at',
            field=models.DateTimeField(blank=True, help_text='When the final letter was forwarded to HOD by ADR/Management.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='staff_forwarded_at',
            field=models.DateTimeField(blank=True, help_text='When the final letter was forwarded to the staff applicant by HOD/ADR/Management.', null=True),
        ),
    ]
