# Generated by Django 5.2.13 on 2026-06-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_add_forwarded_at_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='field_area',
            field=models.CharField(blank=True, default='', help_text='Area where the student intends to conduct the field attachment.', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_decision_reason',
            field=models.TextField(blank=True, default='', help_text="HR's reason on accept/reject — included in the acceptance/rejection letter."),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_address',
            field=models.CharField(blank=True, default='', help_text="Applicant's postal address for correspondence.", max_length=200),
        ),
    ]
