# Generated by Django 5.2.13 on 2026-08-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_application_field_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='programme_duration_unit',
            field=models.CharField(blank=True, choices=[('months', 'Months'), ('years', 'Years')], default='', help_text='months | years — unit for programme_duration_value.', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='programme_duration_value',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Length of the further-studies programme, counted in programme_duration_unit.', null=True),
        ),
    ]
