# Generated by Django 5.2.13 on 2026-04-08 20:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^MMH-\\d{4}-\\d{4}$', 'Must match MMH-YYYY-XXXX.')])),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('working_site', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=50)),
                ('date_employed', models.DateField()),
            ],
            options={
                'db_table': 'employee_profiles',
                'ordering': ['employee_number'],
            },
        ),
    ]
