# Generated by Django 5.2.13 on 2026-04-16 08:22

import django.db.models.deletion
from django.db import migrations, models


def forwards_port_directory_strings(apps, schema_editor):
    EmployeeProfile = apps.get_model("employees", "EmployeeProfile")
    Department = apps.get_model("hospital_directory", "Department")
    Designation = apps.get_model("hospital_directory", "Designation")
    WorkingSite = apps.get_model("hospital_directory", "WorkingSite")

    for ep in EmployeeProfile.objects.all():
        fields: list[str] = []
        legacy_dept = getattr(ep, "_legacy_department", None) or ""
        legacy_des = getattr(ep, "_legacy_designation", None) or ""
        legacy_site = getattr(ep, "_legacy_working_site", None) or ""
        if legacy_dept.strip():
            name = legacy_dept.strip()[:200]
            d = Department.objects.filter(name__iexact=name).first()
            if d is None:
                d = Department.objects.create(name=name, code="", sort_order=0)
            ep.department_id = d.pk
            fields.append("department_id")
        if legacy_des.strip():
            name = legacy_des.strip()[:150]
            d = Designation.objects.filter(name__iexact=name).first()
            if d is None:
                d = Designation.objects.create(name=name, sort_order=0)
            ep.designation_id = d.pk
            fields.append("designation_id")
        if legacy_site.strip():
            name = legacy_site.strip()[:150]
            s = WorkingSite.objects.filter(name__iexact=name).first()
            if s is None:
                s = WorkingSite.objects.create(name=name, sort_order=0)
            ep.working_site_id = s.pk
            fields.append("working_site_id")
        if fields:
            ep.save(update_fields=fields)


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
        ("hospital_directory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="department",
            new_name="_legacy_department",
        ),
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="designation",
            new_name="_legacy_designation",
        ),
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="working_site",
            new_name="_legacy_working_site",
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hospital_directory.department",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hospital_directory.designation",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="working_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hospital_directory.workingsite",
            ),
        ),
        migrations.RunPython(forwards_port_directory_strings, backwards_noop),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="_legacy_department",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="_legacy_designation",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="_legacy_working_site",
        ),
    ]
