# Generated by Django 5.2.13 on 2026-04-20 09:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_hospitalstaff_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_\\.]+$', 'Use lowercase capability code.')])),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='general', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'staff_capabilities_catalog',
                'ordering': ['module', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_\\.]+$', 'Use lowercase code, e.g. hod or training_manager.')])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'staff_roles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='hospitalstaff',
            options={'ordering': ['staff_number']},
        ),
        migrations.AlterField(
            model_name='hospitalstaff',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hospitalstaff',
            name='staff_number',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^((MMH-\\d{4}-\\d{4})|(H\\d{3}))$', 'Must match MMH-YYYY-XXXX or practice staff id H### (e.g. H001).')]),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='employees.staffrole'),
        ),
        migrations.CreateModel(
            name='StaffCapabilityOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], default='grant', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_overrides', to='employees.staffcapability')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to='employees.hospitalstaff')),
            ],
            options={
                'db_table': 'staff_capability_overrides',
                'constraints': [models.UniqueConstraint(fields=('staff', 'capability', 'mode'), name='uniq_staff_capability_override')],
            },
        ),
        migrations.CreateModel(
            name='StaffRoleCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='employees.staffcapability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='employees.staffrole')),
            ],
            options={
                'db_table': 'staff_role_capabilities',
                'constraints': [models.UniqueConstraint(fields=('role', 'capability'), name='uniq_staff_role_capability')],
            },
        ),
    ]
