# Generated by Django 5.2.13 on 2026-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_parent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_parent__af81a0_idx',
            old_name='notif_parent_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('submission', 'Submission'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('revision', 'Revision'), ('field_placement_published', 'Field placement published')], max_length=50),
        ),
    ]
